[phases.setup]
nixPkgs = [
  "chromium",
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "xorg.libX11",
  "xorg.libxcb",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxkbcommon",
  "mesa",
  "expat",
  "libdrm",
  "alsa-lib",
  "cups"
]
